name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: test
        run: OUTPUT=$(docker-compose up --exit-code-from frontend_test | tail -1) && echo $OUTPUT
        shell: bash
      -
        name: Set up QEMU
        if: steps.main.outputs.OUTPUT == 0
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        if: steps.main.outputs.OUTPUT == 0
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: steps.main.outputs.OUTPUT == 0
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      -
        name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      
      -
        name: Build and push
        if: steps.main.outputs.OUTPUT == 0
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend_twitterclone:latest

      - 
        name: Restart deployment
        run: kubectl rollout restart deployment/twitterclone-team3-deployment
